version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r requirements.txt pylint
  pre_build:
    commands:
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py --fail-under=8.0
      - pylint $CODEBUILD_SRC_DIR/store_inventory/*.py --fail-under=8.0
      - pylint $CODEBUILD_SRC_DIR/store/*.py --disable=C,E1101 --fail-under=8.0
  build:
    commands:
      - cd store
      - pytest
      - cd ..

artifacts:
  files:
    - "**/*"
