version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      
    commands:
      - pip install --upgrade pip
      - python -m venv env
      - source env/bin/activate
      - pip install -r requirements.txt pylint
      
  pre_build:
    commands:
      - python --version
      - ls
      - echo "Running pylint on project root..."
      - pylint --disable=C *.py 
      - echo "Running pylint on store_inventory..."
      - pylint --disable=C store_inventory/**/*.py
artifacts:
  files:
    - '**/*'
